dist: xenial
sudo: false
language: cpp

git:
  submodules: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - CORES=$(grep -c ^processor /proc/cpuinfo)
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake -DBUILD_TESTING=TRUE .
  - make -j $CORES -l $CORES

# safelist
branches:
  only:
    - master
